### ISSUE TITLE
.env security

### ISSUE THREAD

**Issue by jpmelnik** [roots/docs#104]
Is it safe to have an .env file?

**Comment by mtx-z** [comment]
I think it is if you prevent HTTP access to it (htaccess/nginx/apache easily done).

**Comment by jpmelnik** [comment]
Thanks!

**Comment by retlehs** [comment]
`.env` is not accessible by the web in a bedrock structure. please use https://discourse.roots.io/ to ask questions and get support. this repo is for docs suggestions and contributions
