### ISSUE TITLE
Best way to globally include PHP files

### ISSUE THREAD

**Issue by mtx-z** [roots/docs#105]
## Submit a feature request

- [X ] I've read the [guidelines for Contributing to Roots Projects](https://github.com/roots/guidelines/blob/master/CONTRIBUTING.md)
- [ ] This is a suggestion for new documentation
- [ ] This is a suggestion for improving the current documentation
- [ ] This is a bug report
- [ ] This request isn't a duplicate of an [existing issue](https://github.com/roots/docs/issues)

---

Hello !
I'm wandering what is the best way to load/include PHP files globally, like we would do including it in our `functions.php` file. 
I thought that the `composer.json`: 
```
"autoload": {
    "psr-4": {
      "App\\": "app/"
    }
  },

```
was enough to load all files within `/app` directory, but it's not. I see that default `/app/*.php` files are loaded  by the `array_map` from `function.php`, wich have a hardcoded "`../app/{$file}.php`" pattern. 

I finaly added to my `composer.json`
```
"autoload": {
    "psr-4": {
      "App\\": "app/"
    },
    "files": [
      "app/lib-autoload.php"
    ]
  },
```

with in `lib-autoload.php` a simple (but maybe not good?)
```
$files = glob(__DIR__ . '/lib/**/*.php');
if ($files === false) {
    throw new RuntimeException("Failed to glob for function files");
}
foreach ($files as $file) {
    require_once $file;
}
unset($file, $files);
```

To load all files from my `/app/lib` directory. 

Is there any better/official way to load some files ? 
I thought about placing them in controllers, but this is global like Taxonomy registration and stuff. 
Those are not PHP Class, and not need to be namespaced (general filter/action mostly, helpers...). 

Thanks a lot !

**Comment by retlehs** [comment]
please use https://discourse.roots.io/ to ask questions and get support. this repo is for docs suggestions and contributions 

related thread https://discourse.roots.io/t/what-is-the-right-way-to-include-custom-function-in-sage-9/8410
