### ISSUE TITLE
How to include reversion image background to CSS?

### ISSUE THREAD

**Issue by weilinzung** [roots/docs#115]
this one seems only work on the inline image, but not for the image on CSS.

https://github.com/roots/docs/blob/sage-9/sage/theme-development-and-building.md#images-in-template-files

- Use this one would have to run the rebuild commond to make the image to the DIST folder during the dev process if I am adding new images;
`<?php echo get_template_directory_uri() . '/dist/images/xxx.png';?>`

- use this `background-image: url(../images/xxx.png);` seems not working on the Sage 9 because all the images are adding hash for reversion.

**Comment by weilinzung** [comment]
I view on `http://localhost:8888/blog/`.

CSS inspector give me this path and said Failed to load resource: the server responded with a status of 404 (Not Found): `background-image: url(**/wp-content/themes/test-theme/dist**/images/xxx_3e39436b.png);`

the bold part should not be there instead like this: background-image: url(../images/xxx_3e39436b.png);

**Comment by kalenjohnson** [comment]
@weilinzung what do you have set here? https://github.com/roots/sage/blob/9.0.0-beta.4/resources/assets/config.json#L11-L12

**Comment by retlehs** [comment]
please use https://discourse.roots.io/ for support

**Comment by weilinzung** [comment]
```
"publicPath": "/wp-content/themes/test-theme",
"devUrl": "http://localhost:8888/build-blog",
```

ON dev server 3000 is fine, but when I build all the things then will on 8888 will become this 
`http://localhost:8888/wp-content/themes/test-theme/dist/images/xxx_3e39436b.png`
instead of
`http://localhost:8888/blog/wp-content/themes/test-theme/dist/images/xxx_3e39436b.png`

I think is something a bug if not do with Bedrock install, thanks!

@kalenjohnson
