### ISSUE TITLE
Minor issue: should be app/ not src/

### ISSUE THREAD

**Issue by xaliber** [roots/docs#127]
## Submit a feature request or bug report

- [ ] I've read the [guidelines for Contributing to Roots Projects](https://github.com/roots/guidelines/blob/master/CONTRIBUTING.md)
- [ ] This is a suggestion for new documentation
- [x] This is a suggestion for improving the current documentation
- [ ] This is a bug report
- [ ] This request isn't a duplicate of an [existing issue](https://github.com/roots/docs/issues)

Replace any `X` with your information.

---

## Suggestion for new/improved documentation

(delete this section if not applicable)

**What is the URL for the current documentation (if applicable)?**

https://github.com/roots/docs/blob/docs/sage/theme-configuration-and-setup.md

**How can the documentation be improved?**

Minor issue, it's still referring to `src/setup.php` instead of `app/setup.php`

**How will this benefit users?**

Won't confuse newbies.

**Comment by retlehs** [comment]
fixed, thanks. feel free to submit a PR in the future ;D
