### ISSUE TITLE
Add FAQ page for questions like "Can I use Bedrock with x?"

### ISSUE THREAD

**Issue by knowler** [roots/docs#142]
## Submit a feature request or bug report

- [x] I've read the [guidelines for Contributing to Roots Projects](https://github.com/roots/guidelines/blob/master/CONTRIBUTING.md)
- [x] This is a suggestion for new documentation
- [ ] This is a suggestion for improving the current documentation
- [ ] This is a bug report
- [x] This request isn't a duplicate of an [existing issue](https://github.com/roots/docs/issues)

Replace any `X` with your information.

---

## Suggestion for new/improved documentation

**What is the URL for the current documentation (if applicable)?**

N/A

**How can the documentation be improved?**

It would be great to have an FAQ page in the docs for questions about theme and plugin compatibility and perhaps other questions people may have (i.e. shared hosting). This suggestion is specifically for Bedrock, but I guess Sage and Trellis could probably be benefited by FAQ pages as well.

**How will this benefit users?**

It will make this information more accessible to users and will save them from needing to scour Discourse for answers.

**Is there a related [Discourse](https://discourse.roots.io/) thread (please link them)?**

Not really. But questions like [this](https://discourse.roots.io/t/pairing-bedrock-with-premium-themes-such-as-astra-or-generatepress-as-the-parent-theme/12227).

**Comment by swalkinshaw** [comment]
I agree 👍 

Would you like to start a page on it?

**Comment by retlehs** [comment]
i am pretty anti-FAQ ([example](https://gds.blog.gov.uk/2013/07/25/faqs-why-we-dont-have-them/), [another example](https://pty.pe/bad-ux-faqs/)) and would prefer to explore alternative options

we could introduce a new 'compatibility' page to the bedrock docs specifically — where we'd explain that bedrock is compatible with pretty much everything... and if something doesn't work, explain how it's not bedrock's fault and how to communicate to plugin/theme authors about not doing things like trying to include `wp-load.php`

**Comment by knowler** [comment]
@retlehs I suspected so. A 'compatibility' page is a good idea. Questions regarding theme/plugin compatibility or even shared hosting could be included there, however, the latter could be addressed on [Deploying Bedrock](https://roots.io/bedrock/docs/deploying-bedrock/) page. It also might be good to find somewhere to address the misconception that one has to use Sage with Bedrock.

@swalkinshaw I can give it a shot. I’m not sure if I’d be able to give the most knowledgeable answers, but I’ll try. Since this is a new page, should I still submit a PR?

**Comment by retlehs** [comment]
can't submit new pages via github PR's, but here's a start: https://roots.io/bedrock/docs/bedrock-compatibility/

@knowler any added info to the deploying bedrock page would be great, that one is very outdated :sweat:
