### ISSUE TITLE
Update documentation to clarify the role of soberwp/controller

### ISSUE THREAD

**Issue by pkarjala** [roots/docs#150]
## Submit a feature request or bug report

- [X] I've read the [guidelines for Contributing to Roots Projects](https://github.com/roots/guidelines/blob/master/CONTRIBUTING.md)
- [X] This is a suggestion for new documentation
- [X] This is a suggestion for improving the current documentation
- [ ] This is a bug report
- [X] This request isn't a duplicate of an [existing issue](https://github.com/roots/docs/issues)

Replace any `X` with your information.

---

## Suggestion for new/improved documentation

(delete this section if not applicable)

**What is the URL for the current documentation (if applicable)?**

https://roots.io/sage/docs/theme-configuration-and-setup/
https://roots.io/sage/docs/blade-templates/

**How can the documentation be improved?**

Currently the soberwp/controller package is included with Sage 9.  However, recent updates to Controller have broken functionality with regards to how filters are supposed to work in the Sage 9 documentation for passing data to templates (see https://roots.io/sage/docs/blade-templates/).

Through various discussions, it has been mentioned that soberwp/controller is an optional part of Sage 9.  However, the documentation does not currently make this clear, or offer instructions on how to remove soberwp/controller should the user not desire to utilize it.

Furthermore, filters are promoted as the proper way to do data passing to templates in Sage 9, but they do not work as of this writing (see https://github.com/soberwp/controller/issues/80) due to conflicts with soberwp/controller.

The documentation should be altered to clarify that soberwp/controller is optional, and can be removed by altering `composer.json` and running `composer update && composer dump-autoload`.

**How will this benefit users?**

Clarity in the usage of soberwp/controller and its optional use in Sage 9, as well as instructions on removing it if it is not desired in a base install.

**Is there a related [Discourse](https://discourse.roots.io/) thread (please link them)?**

https://discourse.roots.io/t/sage-9-passing-acf-data-via-blade-not-working/11641/
https://discourse.roots.io/t/passing-data-between-filters-and-templates-not-working/12718/
https://discourse.roots.io/t/using-controllers-or-filters-to-output-custom-fields/11812/

**Comment by retlehs** [comment]
long overdue. thank you for making this issue

**Comment by pkarjala** [comment]
There will probably need to be additional documentation and/or changes to the default install, as removing the `soberwp/controller` line from the `composer.json` file and running `composer update && composer dump-autoload` will break a default Sage 9 install, due to references to functions in `app/controllers/app.php` in the base install:

`resources/views/partials/page-header.blade.php` line 2:
`<h1>{!! App::title() !!}</h1>`

**Comment by darrenjacoby** [comment]
New release of Controller will respect data passed in from add_filter, as per the Sage documentation. 

https://github.com/soberwp/controller/issues/80#event-1756933944
