### ISSUE TITLE
Just want to make sure I'm doing this right

### ISSUE THREAD

**Issue by ryanbuiltthat** [roots/docs#22]
Is this possible to install? Trellis that is, if I'm running a web admin like Plesk? I can proxy a subdomain with nginx to a different root location, that's nothing. But just wondering if all the other dependencies would work/conflict?

**Comment by swalkinshaw** [comment]
This isn't the place to ask for personal support questions. You can visit our forums at https://discourse.roots.io/ and search for existing topics as well.
