### ISSUE TITLE
Missing quotation marks

### ISSUE THREAD

**Issue by masoninthesis** [roots/docs#25]
ansible-playbook deploy.yml -vvvv -e "site=<domain> env=<environment>

to:

ansible-playbook deploy.yml -vvvv -e "site=<domain> env=<environment>"

**Comment by retlehs** [comment]
PR's almost always accepted here for stuff like this... are you talking about on the trellis troubleshooting docs page?

**Comment by swalkinshaw** [comment]
Fixed in 3fdd9cf6381c2ba4f5f563753e2e702128fc00c6
