### ISSUE TITLE
`{{ site }}` is rendered as empty `<code></code>`

### ISSUE THREAD

**Issue by TangRufus** [roots/docs#251]
* [x] I've read the [guidelines for Contributing to Roots Projects](https://github.com/roots/.github/blob/master/CONTRIBUTING.md)
* [x] This request isn't a duplicate of an existing issue
* [x] I've read the [docs](https://roots.io/documentation/) and followed them (if applicable)
* [x] This is not a personal support request that should be posted on the [Roots Discourse](https://discourse.roots.io/) community

https://github.com/roots/docs/blob/c5dbd212bd77c17736dfe288aa4b0973ffded3d7/docs/trellis/master/deployments.md#L132

``{{ site }}`` is rendered as empty `<code></code>` on https://roots.io/docs/trellis/master/deployments/#custom-tasks

Question: What is the correct syntax to display/escape `{{ site }}` on vuepress?

**Comment by swalkinshaw** [comment]
Backslashes might work for the curly braces? Or maybe use more explicit html like https://stackoverflow.com/a/63614209

**Comment by TangRufus** [comment]
`::: v-pre` works
See: https://vuepress.vuejs.org/guide/using-vue.html#escaping
