### ISSUE TITLE
Tailwind-specific build won't compile 

### ISSUE THREAD

**Issue by lcottingham** [roots/docs#261]
* [x] I've read the [guidelines for Contributing to Roots Projects](https://github.com/roots/.github/blob/master/CONTRIBUTING.md)
* [x] This request isn't a duplicate of an existing issue
* [x] I've read the [docs](https://roots.io/documentation/) and followed them (if applicable)
* [x] This is not a personal support request that should be posted on the [Roots Discourse](https://discourse.roots.io/) community

## Description

Building project with tailwind will not compile on `yarn build`. Resulting error is:

```
Module build failed: ModuleBuildError: Module build failed: ValidationError: Invalid options object. PostCSS Loader has been initialized using an options object that does not match the API schema.
 - options has an unknown property 'plugins'. These properties are valid:
   object { postcssOptions?, execute?, sourceMap? }
```

Seems to be related to PostCSS compatibility in the dependencies. Possible solution offered by downgrading the `postcss-loader` version outlined here [https://github.com/JeffreyWay/laravel-mix/issues/2471](https://github.com/JeffreyWay/laravel-mix/issues/2471)

## Steps to reproduce

1. `composer create-project roots/sage theme-name` + complete CLI steps
2. select Tailwind CSS (option 5) on the last steps
3. `yarn && yarn build`

**Expected behavior:**
A successful build...

**Actual behavior:**
The error outlined above.. traced to `main.scss` compilation

**Comment by nielszandberg** [comment]
I have the same issue

**Comment by yalass** [comment]
Same issue, also when installing Tailwind. I've tried changing PostCSS, I saw someone say to try changing Node versions, neither worked. I noticed this in Tailwind docs: 

Laravel Mix doesn't support PostCSS 8 yet (but it's coming soon) so you need to install the Tailwind CSS v2.0 PostCSS 7 compatibility build for now as we've shown above. 

I don't think this would matter, but I know Sage uses Laravel components like Blade, so my next attempt is to try it. 

Here's the complete error: 

 ERROR  Failed to compile with 1 errors                                                                                                                                                                                                          7:59:33 AM

 error  in ./resources/assets/styles/main.scss

Module build failed: ValidationError: Invalid options object. PostCSS Loader has been initialized using an options object that does not match the API schema.
 - options has an unknown property 'plugins'. These properties are valid:
   object { postcssOptions?, execute?, sourceMap? }
    at validate (/Users/yalass/dev/site/web/app/themes/vde-theme/node_modules/schema-utils/dist/validate.js:104:11)
    at Object.loader (/Users/yalass/dev/site/web/app/themes/vde-theme/node_modules/postcss-loader/dist/index.js:43:29)

 @ ./resources/assets/styles/main.scss 2:14-357 21:1-42:3 22:19-362
 @ multi ./resources/assets/build/util/../helpers/hmr-client.js ./scripts/main.js ./styles/main.scss

**Comment by swalkinshaw** [comment]
Is it an issue with the docs themselves, or Sage? Seems like this issue should be opened on Sage

**Comment by nielszandberg** [comment]
It's an issue with Sage, there is already an issue opened in the Sage repository

**Comment by alwaysblank** [comment]
This appears to be the same as this issue (https://github.com/roots/sage/issues/2580) so I'm closing as a duplicate. If you have addition debug information, please post it over there.

Additionally, this repo is _only_ for the Sage documentation. If you are reporting a bug in Sage, please do so in the [Sage issues](https://github.com/roots/sage/issues/).
