### ISSUE TITLE
don't add /wp to SITE_URL

### ISSUE THREAD

**Issue by udosenakane** [roots/docs#264]
Is possible to remove /wp from SITE_URL

* [ ] I've read the [guidelines for Contributing to Roots Projects](https://github.com/roots/.github/blob/master/CONTRIBUTING.md)
* [ ] This request isn't a duplicate of an existing request
* [ ] This is not a personal support request that should be posted on the [Roots Discourse](https://discourse.roots.io/) community

## Summary

One paragraph explanation of the feature.

## Motivation

Why are we doing this? What use cases does it support? What is the expected outcome?

**Comment by retlehs** [comment]
howdy :wave: please post questions over at https://discourse.roots.io/
