### ISSUE TITLE
Please add example of multiple mu-plugins to documentation.

### ISSUE THREAD

**Issue by eavonius** [roots/docs#291]
* [x ] I've read the [guidelines for Contributing to Roots Projects](https://github.com/roots/.github/blob/master/CONTRIBUTING.md)
* [ x] This request isn't a duplicate of an existing request
* [ ]x This is not a personal support request that should be posted on the [Roots Discourse](https://discourse.roots.io/) community

## Summary

Would love it if y'all added a line to the docs showing how to add multiple mu-plugins here:

https://roots.io/docs/bedrock/master/composer/#force-plugin-to-be-mu-plugin

Took lonoger than it should have to dig it up from this github issue:

https://github.com/roots/bedrock/issues/132#issuecomment-68763671

## Motivation

This will help people with using bedrock.

**Comment by retlehs** [comment]
:+1: would you mind submitting a PR?
