### ISSUE TITLE
Add section to Roots Trellis documenation on Composer HTTP authentication

### ISSUE THREAD

**Issue by jonathanbossenger** [roots/docs#303]
* [x] I've read the [guidelines for Contributing to Roots Projects](https://github.com/roots/.github/blob/master/CONTRIBUTING.md)
* [x] This request isn't a duplicate of an existing request
* [x] This is not a personal support request that should be posted on the [Roots Discourse](https://discourse.roots.io/) community

## Summary

Update the [Roots Trellis](https://roots.io/docs/trellis) documentation to include a section on the new HTTP composer authentication method added in [https://github.com/roots/trellis/pull/1091](https://github.com/roots/trellis/pull/1091)

## Motivation

[https://github.com/roots/trellis/pull/1091](https://github.com/roots/trellis/pull/1091) added support for HTTP basic authentication for multiple composer repositories. I would like to contribute a section in the docs to reflect this, with examples (eg https://discourse.roots.io/t/gitlab-private-repo-as-composer-package/20592/19). I'm in charge of the technical documentation at Delicious Brains, and I'm updating our plugin composer documentation to point folks to this new method. It makes sense to also help update the official docs, to be able to add a link to them.

**Comment by jonathanbossenger** [comment]
@TangRufus I'm opening this issue as a response to your call for a doc update [here](https://github.com/roots/trellis/pull/1091#issuecomment-893493973). I'd like to use this issue to discuss the contents of the doc update before I create the PR.

The first question I do have is, should this be its own page in the Trellis documentation, or should it be part of an existing page? 

I note that the one place that does have a page on Composer is the [Bedrock documentation](https://roots.io/docs/bedrock/master/composer/), but I'm not sure if it makes sense to add this here?

Any comments/suggestions are welcome.

**Comment by tangrufus** [comment]
> The first question I do have is, should this be its own page in the Trellis documentation, or should it be part of an existing page?

Adding a new "Bedrock Integration" page under [Trellis' Digging Deeper](https://github.com/roots/docs/blob/baef1547c160669eb2fa3852c69b714d43ad9532/docs/trellis/master.js#L36-L43) section would be great.

> I note that the one place that does have a page on Composer is the Bedrock documentation, but I'm not sure if it makes sense to add this here?

For the [Bedrock documentation](https://roots.io/docs/bedrock/master/composer/) page, we can either leave it as it is or add a link to your new Trellis page, whichever you see fits.

---

Few things about https://github.com/roots/trellis/pull/1091 
- the passwords should not be stored as plain text, https://roots.io/docs/trellis/master/vault/
- passwords cannot be `null` or empty strings, https://github.com/roots/trellis/issues/1306
- having [`auth.json`](https://getcomposer.org/doc/articles/authentication-for-private-packages.md#authentication-in-auth-json-per-project) checked under git or templating `auth.json` via ansible is usually wrong (not the best practice)
- only [`http-basic`](https://getcomposer.org/doc/articles/authentication-for-private-packages.md#authentication-principles) is supported, PRs are welcomed

**Comment by jonathanbossenger** [comment]
Created PR to add new Bedrock Integration doc. Feedback would be greatly appreciated.

**Comment by jonathanbossenger** [comment]
Thanks for the feedback folks. Do you know how long it takes for the new doc page to be live?

**Comment by swalkinshaw** [comment]
Docs get autodeployed on merge. It's live at https://roots.io/docs/trellis/master/composer-http-basic-authentication/

You'll probably have to do a hard refresh due to service worker caching.

**Comment by tomektomczuk** [comment]
Would composer_authentications works with github-oauth?

For example:
composer_authentications:
      - {"github-oauth": {"github.com": "XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX"}}
