### ISSUE TITLE
Indicate need to navigate to "trellis" subdir before running "vagrant up"

### ISSUE THREAD

**Issue by ababra** [roots/docs#39]
## Submit a feature request or bug report
- [X] I've read the [guidelines for Contributing to Roots Projects](https://github.com/roots/guidelines/blob/master/CONTRIBUTING.md)
- [ ] This is a suggestion for new documentation
- [X] This is a suggestion for improving the current documentation
- [ ] This is a bug report
- [X] This request isn't a duplicate of an [existing issue](https://github.com/roots/docs/issues)

Replace any `X` with your information.

---
## Suggestion for new/improved documentation

**What is the URL for the current documentation (if applicable)?**

https://roots.io/trellis/docs/local-development-setup/

**How can the documentation be improved?**

In step 3, "Run vagrant up.", please indicate that you need to navigate to the "trellis" subfolder first in the project directory. If you attempt to run "vagrant up" from any other directory, you receive the following error from Vagrant:

> A Vagrant environment or target machine is required to run this
> command. Run `vagrant init` to create a new Vagrant environment. Or,
> get an ID of a target machine from `vagrant global-status` to run
> this command on. A final option is to change to a directory with a
> Vagrantfile and to try again.

**How will this benefit users?**

Easier for newbies to understand. 

**Is there a related [Discourse](https://discourse.roots.io/) thread (please link them)?**

X

**Comment by swalkinshaw** [comment]
I've updated the wording in those steps. Thanks!
