### ISSUE TITLE
Bug: Support of SCSS

### ISSUE THREAD

**Issue by vitaliidmytrieiev** [roots/docs#406]
### Terms

- [X] I have read the [guidelines for Contributing to Roots Projects](https://github.com/roots/.github/blob/master/CONTRIBUTING.md)
- [X] This request is not a duplicate of an existing issue
- [X] I have read the [docs](https://roots.io/docs/) and followed them (if applicable)
- [X] I have seached the [Roots Discourse](https://discourse.roots.io/) for answers and followed them (if applicable)
- [X] This is not a personal support request that should be posted on the [Roots Discourse](https://discourse.roots.io/) community

#### What's wrong?
I cannot enable the support of SCSS on clear theme Sage v10+

#### What have you tried?
After clear installation and trying to do all steps from this link. https://docs.roots.io/sage/10.x/css-frameworks/#add-bootstrap
When trying to execute yarn build i see such error:
<img width="1126" alt="image" src="https://user-images.githubusercontent.com/98816834/168641195-28c8df73-0cc3-4b7f-a25c-d584bf9cfdb0.png">

When i trying to run command yarn dev I see list of errors:
![image](https://user-images.githubusercontent.com/98816834/168761776-b2de46e6-e288-4c48-9aa2-2c99171a46bd.png)

Are there any suggestions on how can i solve those problems? 

### Steps To Reproduce

1. Install a theme from official documentation Sage v10+
2. Do all steps from this link https://docs.roots.io/sage/10.x/css-frameworks/#add-bootstrap
3. Run yarn build or/and yarn dev
4. See errors.

### Expected Behavior

Build correctly files

### Actual Behavior

Error while trying to compile files

### Versions

10.1.6

**Comment by xdvz** [comment]
I had a similar issue while adding bud-sass. 
In the process, I learned that:
1. I need to use the same versions of dependencies in package.json file;
2. Update all bud dependencies from 5.7.6 to 5.8.1;

Also, this [ticket](https://github.com/roots/docs/issues/328#issue-1075846151) helped me
