### ISSUE TITLE
Feature Request: [Trellis] Add documentation of how to support MailHog on arm64 systems

### ISSUE THREAD

**Issue by jakobmeusburger** [roots/docs#408]
### Terms

- [X] I have read the [guidelines for Contributing to Roots Projects](https://github.com/roots/.github/blob/master/CONTRIBUTING.md)
- [X] This request is not a duplicate of an existing issue
- [X] This is not a personal support request that should be posted on the [Roots Discourse](https://discourse.roots.io/) community

### Summary

If you work on an arm64 system such as Apple M1 MailHog isn't working in the local development environment of Trellis. If the binary is called it instantly fails with `cannot execute binary file: Exec format error`. This is because the geerlingguy.mailhog role doesn't provide platform agnostic binaries. In fact there isn't an official arm64 binary of MailHog out there. But there are user contributed binaries. It is possible to run MailHog with these binaries. In order to accomplish this you have to add
```
mailhog_version: 1.0.1
mailhog_binary_url: "https://github.com/jcalonso/MailHog/releases/download/v1.0.1-arm/MailHog.linux.arm64"
mhsendmail_version: 0.2.0
mhsendmail_binary_url: "https://github.com/evertiro/mhsendmail/releases/download/v0.2.0-M1/mhsendmail_linux_arm64"
``` 
to _group_vars/development/main.yml_.

I spent quite a time of debugging this issue until I found this solution. I suggest adding it to the official documentation to save others this trouble in the future.

#### Why are we doing this?
In order to save others the time used for debugging this issue in the future.
#### What use cases does it support?
Inform the user about the compatibility of arm64 systems and MailHog.
#### What is the expected outcome?
Users with arm64 systems can use MailHog.
#### Potential conflicts / foreseeable issues
Maybe the users, which created the arm64 binaries remove them from their git so that they can't be downloaded anymore.

**Comment by retlehs** [comment]
thanks for the report and the workaround! would you like to submit a PR?

**Comment by jakobmeusburger** [comment]
> thanks for the report and the workaround! would you like to submit a PR?

done: #409
