### ISSUE TITLE
Bug:  multisite-url-fixer is deprecated but recomended

### ISSUE THREAD

**Issue by Trisky** [roots/docs#411]
### Terms

- [X] I have read the [guidelines for Contributing to Roots Projects](https://github.com/roots/.github/blob/master/CONTRIBUTING.md)
- [X] This request is not a duplicate of an existing issue
- [X] I have read the [docs](https://roots.io/docs/) and followed them (if applicable)
- [X] I have seached the [Roots Discourse](https://discourse.roots.io/) for answers and followed them (if applicable)
- [X] This is not a personal support request that should be posted on the [Roots Discourse](https://discourse.roots.io/) community

### Description

Hi There! I'm kinda confused about what to do with the multisite url fixer. I got to know its deprecated because of the warning while running composer install. We use it in production as well!

#### What's wrong?

The plugin repo is archived but it's still recomended to use in the docs.
https://github.com/roots/multisite-url-fixer
https://roots.io/docs/bedrock/master/installation/#multisite

#### Possible solutions

Indicate in the plugins repo why is it deprecated  and what should be done in multisite installs.

Remove plugin reference from the docs.

### Steps To Reproduce

open the docs and read
https://roots.io/docs/bedrock/master/installation/#multisite

### Expected Behavior

plugin is not recomended

### Actual Behavior

The plugin repo is archived but it's still recomended to use in the docs.

### Versions

docs

**Comment by retlehs** [comment]
howdy! the plugin can still be used, but we've archived it due to inactivity/and a lack of maintenance on our end.

we'd be happy to transfer the repo to an org that's actively working with multisite installs and will maintain the repo, or update the docs to a new fork that's actively maintained

**Comment by astratagem** [comment]
I came here to report the same issue. 

> the plugin can still be used, but we've archived it due to inactivity/and a lack of maintenance on our end.

@retlehs Thanks for providing that context. However, your comment appears to be the only place where this reasoning is indicated. I agree with @Trisky that this should be indicated _somewhere_ -- ideally in both the docs and in the plugin repo.

During the onboarding process, it's disconcerting to click the suggested link and then find the repo archived without explanation. Numerous questions would then arise: "is the plugin still necessary for subdomain installs?" / "is the plugin broken?". Many (most?) potential Bedrock+multisite users won't take the time to search the documentation repo's issue tracker to find the answer in a comment.

> we'd be happy to transfer the repo to an org that's actively working with multisite installs and will maintain the repo, or update the docs to a new fork that's actively maintained

In most archived repos I've seen, the former maintainers left a prominent explanation as to why the repo was archived and suggestions for alternatives (if applicable). It would also be prime real estate for extending the offer to transfer ownership to another organisation that would maintain the plugin or request other help.

**Comment by retlehs** [comment]
@montchr Thanks for commenting — these are great points and I agree with you. This repo was archived in a batch with other old repos that don't have as much use/activity. I'll get a note added to the https://github.com/roots/multisite-url-fixer README.
