### ISSUE TITLE
Bug: Code blocks not rendering on website

### ISSUE THREAD

**Issue by astratagem** [roots/docs#456]
### Terms

- [X] I have read the [guidelines for Contributing to Roots Projects](https://github.com/roots/.github/blob/master/CONTRIBUTING.md)
- [X] This request is not a duplicate of an existing issue
- [X] I have read the [docs](https://roots.io/docs/) and followed them (if applicable)
- [X] I have seached the [Roots Discourse](https://discourse.roots.io/) for answers and followed them (if applicable)
- [X] This is not a personal support request that should be posted on the [Roots Discourse](https://discourse.roots.io/) community

#### What's wrong?

Code blocks on documentation website are not rendering:

![image](https://user-images.githubusercontent.com/1757914/224811064-a87caf4d-a502-43ba-9c6c-ba421dd3c84e.png)

#### What have you tried?

n/a

#### What insights have you gained?

n/a

#### Possible solutions

?

#### Temporary workarounds

?

### Steps To Reproduce

1. Go to any page with a code block/snippet e.g. <https://roots.io/sage/docs/tailwind-css/>

### Expected Behavior

Content should show up on site.

### Actual Behavior

Content does not render.

![image](https://user-images.githubusercontent.com/1757914/224811544-6b377198-cd48-4f5a-93e2-5302ea40b892.png)

### Versions

docs

**Comment by retlehs** [comment]
Can you try a hard refresh?

**Comment by retlehs** [comment]
I was able to consistently reproduce this — replaced our client side syntax highlighting with a server side solution

Thank you for the report
