### ISSUE TITLE
configure 3rd party packages ?

### ISSUE THREAD

**Issue by v3nt** [roots/docs#50]
## Submit a feature request or bug report

- [ ] I've read the [guidelines for Contributing to Roots Projects](https://github.com/roots/guidelines/blob/master/CONTRIBUTING.md)
- [ ] This is a suggestion for new documentation
- [X] This is a suggestion for improving the current documentation
- [ ] This is a bug report
- [ ] This request isn't a duplicate of an [existing issue](https://github.com/roots/docs/issues)

ie 
favicon https://www.npmjs.com/package/favicon 
deployment https://www.npmjs.com/package/deployment
...

**How can the documentation be improved?**

some examples of how we now do this without grunt / gulp.

**How will this benefit users?**

I use a lot of 3rd party packages and there can be quite a lot to configure.

**Comment by retlehs** [comment]
this already exists on the sage 9 branch of this repo

https://github.com/roots/docs/blob/a3e8901665d5995b5a14be4c2e1a880ee153fd00/sage/theme-development-and-building.md#3rd-party-packages

**Comment by v3nt** [comment]
Thanks @retlehs but I can't see anything about configuring installed packages? 

The examples give don't need any config files. I've had a good look through the in progress docs.

ie grunt-iconfont https://www.npmjs.com/package/grunt-iconfont
Where / how do we add this config?
```
grunt.initConfig({
  iconfont: {
    options: {
      fontName: "my-font-name"
    },
    your_target: {
        src: 'glyphs/*.svg',
        dest: 'font/'
    }
  },
})

```
Where do we configure these now as there is no Gruntfile.js or Gulpfile.js?
