### ISSUE TITLE
Add notes about in-memory file system

### ISSUE THREAD

**Issue by QWp6t** [roots/docs#52]
A common confusion among users is that certain files aren't written to the filesystem during development.

We can help clarify things by explaining to users that webpack-dev-middleware uses an in-memory filesystem.

> The webpack-dev-middleware is a small middleware for a connect-based middleware stack. **It uses webpack to compile assets in-memory and serve them.** When a compilation is running every request to the served webpack assets is blocked until we have a stable bundle.

https://webpack.github.io/docs/webpack-dev-middleware.html

We could maybe research a plugin that will write the in-memory filesystem to disk anyway, such as: https://github.com/gajus/write-file-webpack-plugin

**Comment by retlehs** [comment]
Would be nice to write to the file system anyway since the 404 on dev isn't ideal
