### ISSUE TITLE
Add Trellis docs for resolving local_path on Windows/ansible-local

### ISSUE THREAD

**Issue by QWp6t** [roots/docs#62]
Some genius wrote this:

> The correct way to resolve this is to set your local_path in your wordpress_sites.yml file.
> 
> https://github.com/roots/trellis/blob/master/group_vars/production/wordpress_sites.yml#L11
> 
> I'm guessing that it's currently `../site`, which is resolving to `/vagrant/../site`, which is `/site`, which doesn't exist. You should change that to something like `/srv/www/example.com/current`.
> 
> 
> Alternatively, you can move your Vagrantfile one level up so that it sits alongside your trellis and site folders. This is how we used to do it in roots-example-project. Just make sure to change your `ANSIBLE_PATH` in Vagrantfile to something like `File.join(__dir__, 'trellis')` [[ref](https://github.com/roots/roots-example-project.com/blob/afc2c6adb4ec9b1ef266e8df13882600c7f1c333/Vagrantfile#L6)]. This will put your site files in `/vagrant/site` and your trellis stuff in `/vagrant/trellis`. Now `local_path: ../site` will resolve to `/vagrant/trellis/../site`, which is `/vagrant/site`, which exists.

https://discourse.roots.io/t/trellis-bedrock-sage-on-windows-issue-with-build-before-yml/7825/6

The latter suggestion of moving Vagrantfile up one level has the added benefit of making the settings work cross-platform.

**Comment by swalkinshaw** [comment]
@QWp6t @fullyint is this relevant anymore after recent Windows updates/docs?

Ref: https://github.com/roots/docs/pull/64

**Comment by QWp6t** [comment]
Yeah. In fact, I think https://github.com/roots/trellis/pull/705 might have even made things worse in this regard insofar that there doesn't appear to be a cross-platform way to resolve `local_path` like there used to be. So this might need to be taken to the trellis repo since it could possibly be considered a regression.

**Comment by fullyint** [comment]
Closing. Addressed in roots/trellis#725
