### ISSUE TITLE
Add warning about ecryptfs

### ISSUE THREAD

**Issue by jbicha** [roots/docs#69]
I think it would be nice if the docs mentioned on `installing-trellis` that the project directory must not be in an ecryptfs directory.

ecryptfs is used if the "encrypt my home folder" option is selected during a Ubuntu install. In that case, any directory outside `/home` should work.

See more info at https://github.com/roots/trellis/issues/738

**Comment by swalkinshaw** [comment]
Feel free to do a PR with a note about this 👍

**Comment by retlehs** [comment]
noted on https://roots.io/trellis/docs/local-development-setup/
