### ISSUE TITLE
scss vs css

### ISSUE THREAD

**Issue by zocoloco** [roots/docs#76]
## Submit a feature request or bug report

- [ x] I've read the [guidelines for Contributing to Roots Projects](https://github.com/roots/guidelines/blob/master/CONTRIBUTING.md)
- [ ] This is a suggestion for new documentation
- [ ] This is a suggestion for improving the current documentation
- [x ] This is a bug report
- [ ] This request isn't a duplicate of an [existing issue](https://github.com/roots/docs/issues)

---

## Bug report

(delete this section if not applicable)

**Where is it?**

https://github.com/roots/docs/blob/sage-9/sage/theme-configuration-and-setup.md

**What should it say?**

should css enqueue be:
wp_enqueue_style('sage/main.scss', asset_path('styles/main.scss'), false, null);

instead of how .css - how it's currently written?
wp_enqueue_style('sage/main.css', asset_path('styles/main.css'), false, null);

**Comment by retlehs** [comment]
nope, you always want to reference the compiled css and not the source sass files

**Comment by zocoloco** [comment]
Thanks!
